#!/bin/sh

response=$(curl -k -u admin:admin -X 'GET' 'https://localhost:8888/api/v5_2/virtualnode' -H 'accept: application/json')


world_charity_hash=$(echo $response | jq -r '.virtualNodes[] | select(.holdingIdentity.x500Name | contains("WorldCharity")) | .holdingIdentity.shortHash')
dave_hash=$(echo $response | jq -r '.virtualNodes[] | select(.holdingIdentity.x500Name | contains("Dave")) | .holdingIdentity.shortHash')
alice_hash=$(echo $response | jq -r '.virtualNodes[] | select(.holdingIdentity.x500Name | contains("Alice")) | .holdingIdentity.shortHash')
charlie_hash=$(echo $response | jq -r '.virtualNodes[] | select(.holdingIdentity.x500Name | contains("Charlie")) | .holdingIdentity.shortHash')
notary_service_hash=$(echo $response | jq -r '.virtualNodes[] | select(.holdingIdentity.x500Name | contains("NotaryService")) | .holdingIdentity.shortHash')

sleep 3

curl -k -u admin:admin -X 'POST' \
  "https://localhost:8888/api/v5_2/flow/$world_charity_hash" \
  -H 'accept: application/json' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{
    "clientRequestId": "create-project-1",
    "flowClassName": "com.r3.developers.charity.workflows.ProjectCreationFlow",
    "requestBody": {
        "totalBudget": 0,
        "projectName": "Housing",
        "projectDescription": "Building homes",
        "charityName": "CN=WorldCharity, OU=Test Dept, O=R3, L=London, C=GB",
        "notary": "CN=NotaryService, OU=Test Dept, O=R3, L=London, C=GB"
    }
}' > /dev/null 2>&1
sleep 6

curl -k -u admin:admin -X 'POST' \
  "https://localhost:8888/api/v5_2/flow/$world_charity_hash" \
  -H 'accept: application/json' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{
    "clientRequestId": "get-ID-name",
    "flowClassName": "com.r3.developers.charity.workflows.GetProjectIDGivenProjectName",
    "requestBody": {
        "projectName": "Housing"
    }
}' > /dev/null 2>&1
sleep 10

response=$(curl -k -u admin:admin -X 'GET' \
  "https://localhost:8888/api/v5_2/flow/$world_charity_hash/get-ID-name" \
  -H 'accept: application/json' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=')

flow_result=$(echo $response | jq -r '.flowResult')
projectID=$(echo $flow_result | jq -r '.projectID')



sleep 5

response=$(curl -k -u admin:admin -X 'POST' \
  "https://localhost:8888/api/v5_2/flow/$world_charity_hash" \
  -H 'accept: application/json' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d "{
    \"clientRequestId\": \"get-create-1\",
    \"flowClassName\": \"com.r3.developers.charity.workflows.GetProjectDetailsFlow\",
    \"requestBody\": {
        \"projectID\": \"$projectID\"
    }
}")


sleep 5

response2=$(curl -k -u admin:admin -X 'GET' \
  "https://localhost:8888/api/v5_2/flow/$world_charity_hash/get-create-1" \
  -H 'accept: application/json' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=')

flow_result=$(echo $response2 | jq -r '.flowResult')
projectName=$(echo $flow_result | jq -r '.projectName')
projectDescription=$(echo $flow_result | jq -r '.projectDescription')
totalBudget=$(echo $flow_result | jq -r '.totalBudget')

echo ""
echo "Project Name: $projectName"
echo "Project Description: $projectDescription"
echo "Remaining Funds: $totalBudget"














